// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YClient_htinoco2.Models;

namespace YClient_htinoco2.Migrations
{
    [DbContext(typeof(Valoresc))]
    [Migration("20201104122711_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YClient_htinoco2.Models.Valorestab", b =>
                {
                    b.Property<decimal>("Ndecimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeId")
                        .HasColumnType("int");

                    b.ToTable("Valorestab");
                });
#pragma warning restore 612, 618
        }
    }
}
